// AUTO-GENERATED by scripts-logoflag.cjs — do not edit.
// Drop public/logo.png or public/music.mp3 in, re-run `node scripts-logoflag.cjs`, re-render.
export const HAS_LOGO_FILE = false;
export const HAS_MUSIC_FILE = false;
